---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configexport.kraken-iac.eoinfennessy.com
  resources:
  - configexports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configexport.kraken-iac.eoinfennessy.com
  resources:
  - configexports/finalizers
  verbs:
  - update
- apiGroups:
  - configexport.kraken-iac.eoinfennessy.com
  resources:
  - configexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kraken-iac.eoinfennessy.com
  resources:
  - dependencyrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kraken-iac.eoinfennessy.com
  resources:
  - dependencyrequests/finalizers
  verbs:
  - update
- apiGroups:
  - core.kraken-iac.eoinfennessy.com
  resources:
  - dependencyrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.kraken-iac.eoinfennessy.com
  resources:
  - statedeclarations
  verbs:
  - get
  - list
  - watch
