//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapDependency) DeepCopyInto(out *ConfigMapDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapDependency.
func (in *ConfigMapDependency) DeepCopy() *ConfigMapDependency {
	if in == nil {
		return nil
	}
	out := new(ConfigMapDependency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRequest) DeepCopyInto(out *DependencyRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRequest.
func (in *DependencyRequest) DeepCopy() *DependencyRequest {
	if in == nil {
		return nil
	}
	out := new(DependencyRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRequestList) DeepCopyInto(out *DependencyRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DependencyRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRequestList.
func (in *DependencyRequestList) DeepCopy() *DependencyRequestList {
	if in == nil {
		return nil
	}
	out := new(DependencyRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DependencyRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRequestSpec) DeepCopyInto(out *DependencyRequestSpec) {
	*out = *in
	if in.KrakenResourceDependencies != nil {
		in, out := &in.KrakenResourceDependencies, &out.KrakenResourceDependencies
		*out = make([]KrakenResourceDependency, len(*in))
		copy(*out, *in)
	}
	if in.ConfigMapDependencies != nil {
		in, out := &in.ConfigMapDependencies, &out.ConfigMapDependencies
		*out = make([]ConfigMapDependency, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRequestSpec.
func (in *DependencyRequestSpec) DeepCopy() *DependencyRequestSpec {
	if in == nil {
		return nil
	}
	out := new(DependencyRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyRequestStatus) DeepCopyInto(out *DependencyRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyRequestStatus.
func (in *DependencyRequestStatus) DeepCopy() *DependencyRequestStatus {
	if in == nil {
		return nil
	}
	out := new(DependencyRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KrakenResourceDependency) DeepCopyInto(out *KrakenResourceDependency) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KrakenResourceDependency.
func (in *KrakenResourceDependency) DeepCopy() *KrakenResourceDependency {
	if in == nil {
		return nil
	}
	out := new(KrakenResourceDependency)
	in.DeepCopyInto(out)
	return out
}
